// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Fnf89QeS7e8526AEE5u5tqlHY_LNR9U',
    appId: '1:207180012629:web:c3c3a07944feeb0139c8dc',
    messagingSenderId: '207180012629',
    projectId: 'login-app-fd3b4',
    authDomain: 'login-app-fd3b4.firebaseapp.com',
    storageBucket: 'login-app-fd3b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP7clNVxoEL3smELVGDCRdQvHsuSvYIRE',
    appId: '1:207180012629:android:446518f29f453f7539c8dc',
    messagingSenderId: '207180012629',
    projectId: 'login-app-fd3b4',
    storageBucket: 'login-app-fd3b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGOlTe6Ayf1JX2EoIJYnuvYc5Ku3isNsM',
    appId: '1:207180012629:ios:1fbf1a217773603539c8dc',
    messagingSenderId: '207180012629',
    projectId: 'login-app-fd3b4',
    storageBucket: 'login-app-fd3b4.appspot.com',
    iosClientId: '207180012629-54v0sja06k6o6ko0sfsu7777kg2j9at9.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGOlTe6Ayf1JX2EoIJYnuvYc5Ku3isNsM',
    appId: '1:207180012629:ios:1fbf1a217773603539c8dc',
    messagingSenderId: '207180012629',
    projectId: 'login-app-fd3b4',
    storageBucket: 'login-app-fd3b4.appspot.com',
    iosClientId: '207180012629-54v0sja06k6o6ko0sfsu7777kg2j9at9.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );
}
